version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
    networks:
      - app-network
    container_name: order-calculator-backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network
    container_name: order-calculator-frontend

networks:
  app-network:
    driver: bridge